version: '3'

services:
  users_db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:      
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: nextgen
  redis-server: 
    image: 'redis'
    ports:
      - 6379:6379
